
package pt.uturista.flags;

import java.util.HashMap;
import java.util.Map;

public class World {

    public final static int UNKNOWN = 0;
    public final static int ASIA = 1;
    public final static int EUROPE = 2;
    public final static int AFRICA = 3;
    public final static int OCEANIA = 4;
    public final static int AMERICAS = 5;
    public final static Map<String, Country> WORLD_MAP = new HashMap<String, Country>();
    public final static Country AFGHANISTAN = new Country("afghanistan", "af", "afg", ".af", (R.string.afghanistan), (R.drawable.afghanistan), (ASIA));
    public final static Country ALAND_ISLANDS = new Country("aland_islands", "ax", "ala", ".ax", (R.string.aland_islands), (R.drawable.aland_islands), (EUROPE));
    public final static Country ALBANIA = new Country("albania", "al", "alb", ".al", (R.string.albania), (R.drawable.albania), (EUROPE));
    public final static Country ALGERIA = new Country("algeria", "dz", "dza", ".dz", (R.string.algeria), (R.drawable.algeria), (AFRICA));
    public final static Country AMERICAN_SAMOA = new Country("american_samoa", "as", "asm", ".as", (R.string.american_samoa), (R.drawable.american_samoa), (OCEANIA));
    public final static Country ANDORRA = new Country("andorra", "ad", "and", ".ad", (R.string.andorra), (R.drawable.andorra), (EUROPE));
    public final static Country ANGOLA = new Country("angola", "ao", "ago", ".ao", (R.string.angola), (R.drawable.angola), (AFRICA));
    public final static Country ANGUILLA = new Country("anguilla", "ai", "aia", ".ai", (R.string.anguilla), (R.drawable.anguilla), (AMERICAS));
    public final static Country ANTIGUA_AND_BARBUDA = new Country("antigua_and_barbuda", "ag", "atg", ".ag", (R.string.antigua_and_barbuda), (R.drawable.antigua_and_barbuda), (AMERICAS));
    public final static Country ARGENTINA = new Country("argentina", "ar", "arg", ".ar", (R.string.argentina), (R.drawable.argentina), (AMERICAS));
    public final static Country ARMENIA = new Country("armenia", "am", "arm", ".am", (R.string.armenia), (R.drawable.armenia), (ASIA));
    public final static Country ARUBA = new Country("aruba", "aw", "abw", ".aw", (R.string.aruba), (R.drawable.aruba), (AMERICAS));
    public final static Country AUSTRALIA = new Country("australia", "au", "aus", ".au", (R.string.australia), (R.drawable.australia), (OCEANIA));
    public final static Country AUSTRIA = new Country("austria", "at", "aut", ".at", (R.string.austria), (R.drawable.austria), (EUROPE));
    public final static Country AZERBAIJAN = new Country("azerbaijan", "az", "aze", ".az", (R.string.azerbaijan), (R.drawable.azerbaijan), (ASIA));
    public final static Country BAHAMAS = new Country("bahamas", "bs", "bhs", ".bs", (R.string.bahamas), (R.drawable.bahamas), (AMERICAS));
    public final static Country BAHRAIN = new Country("bahrain", "bh", "bhr", ".bh", (R.string.bahrain), (R.drawable.bahrain), (ASIA));
    public final static Country BANGLADESH = new Country("bangladesh", "bd", "bgd", ".bd", (R.string.bangladesh), (R.drawable.bangladesh), (ASIA));
    public final static Country BARBADOS = new Country("barbados", "bb", "brb", ".bb", (R.string.barbados), (R.drawable.barbados), (AMERICAS));
    public final static Country BELARUS = new Country("belarus", "by", "blr", ".by", (R.string.belarus), (R.drawable.belarus), (EUROPE));
    public final static Country BELGIUM = new Country("belgium", "be", "bel", ".be", (R.string.belgium), (R.drawable.belgium), (EUROPE));
    public final static Country BELIZE = new Country("belize", "bz", "blz", ".bz", (R.string.belize), (R.drawable.belize), (AMERICAS));
    public final static Country BENIN = new Country("benin", "bj", "ben", ".bj", (R.string.benin), (R.drawable.benin), (AFRICA));
    public final static Country BERMUDA = new Country("bermuda", "bm", "bmu", ".bm", (R.string.bermuda), (R.drawable.bermuda), (AMERICAS));
    public final static Country BHUTAN = new Country("bhutan", "bt", "btn", ".bt", (R.string.bhutan), (R.drawable.bhutan), (ASIA));
    public final static Country BOLIVIA = new Country("bolivia", "bo", "bol", ".bo", (R.string.bolivia), (R.drawable.bolivia), (AMERICAS));
    public final static Country BOSNIA_AND_HERZEGOVINA = new Country("bosnia_and_herzegovina", "ba", "bih", ".ba", (R.string.bosnia_and_herzegovina), (R.drawable.bosnia_and_herzegovina), (EUROPE));
    public final static Country BOTSWANA = new Country("botswana", "bw", "bwa", ".bw", (R.string.botswana), (R.drawable.botswana), (AFRICA));
    public final static Country BRAZIL = new Country("brazil", "br", "bra", ".br", (R.string.brazil), (R.drawable.brazil), (AMERICAS));
    public final static Country BRITISH_INDIAN_OCEAN_TERRITORY = new Country("british_indian_ocean_territory", "io", "iot", ".io", (R.string.british_indian_ocean_territory), (R.drawable.british_indian_ocean_territory), (AFRICA));
    public final static Country BRITISH_VIRGIN_ISLANDS = new Country("british_virgin_islands", "vg", "vgb", ".vg", (R.string.british_virgin_islands), (R.drawable.british_virgin_islands), (AMERICAS));
    public final static Country BRUNEI = new Country("brunei", "bn", "brn", ".bn", (R.string.brunei), (R.drawable.brunei), (ASIA));
    public final static Country BULGARIA = new Country("bulgaria", "bg", "bgr", ".bg", (R.string.bulgaria), (R.drawable.bulgaria), (EUROPE));
    public final static Country BURKINA_FASO = new Country("burkina_faso", "bf", "bfa", ".bf", (R.string.burkina_faso), (R.drawable.burkina_faso), (AFRICA));
    public final static Country BURUNDI = new Country("burundi", "bi", "bdi", ".bi", (R.string.burundi), (R.drawable.burundi), (AFRICA));
    public final static Country CAMBODIA = new Country("cambodia", "kh", "khm", ".kh", (R.string.cambodia), (R.drawable.cambodia), (ASIA));
    public final static Country CAMEROON = new Country("cameroon", "cm", "cmr", ".cm", (R.string.cameroon), (R.drawable.cameroon), (AFRICA));
    public final static Country CANADA = new Country("canada", "ca", "can", ".ca", (R.string.canada), (R.drawable.canada), (AMERICAS));
    public final static Country CAPE_VERDE = new Country("cape_verde", "cv", "cpv", ".cv", (R.string.cape_verde), (R.drawable.cape_verde), (AFRICA));
    public final static Country CAYMAN_ISLANDS = new Country("cayman_islands", "ky", "cym", ".ky", (R.string.cayman_islands), (R.drawable.cayman_islands), (AMERICAS));
    public final static Country CENTRAL_AFRICAN_REPUBLIC = new Country("central_african_republic", "cf", "caf", ".cf", (R.string.central_african_republic), (R.drawable.central_african_republic), (AFRICA));
    public final static Country CHAD = new Country("chad", "td", "tcd", ".td", (R.string.chad), (R.drawable.chad), (AFRICA));
    public final static Country CHILE = new Country("chile", "cl", "chl", ".cl", (R.string.chile), (R.drawable.chile), (AMERICAS));
    public final static Country CHINA = new Country("china", "cn", "chn", ".cn", (R.string.china), (R.drawable.china), (ASIA));
    public final static Country CHRISTMAS_ISLAND = new Country("christmas_island", "cx", "cxr", ".cx", (R.string.christmas_island), (R.drawable.christmas_island), (OCEANIA));
    public final static Country COCOS_ISLAND = new Country("cocos_island", "cc", "cck", ".cc", (R.string.cocos_island), (R.drawable.cocos_island), (OCEANIA));
    public final static Country COLOMBIA = new Country("colombia", "co", "col", ".co", (R.string.colombia), (R.drawable.colombia), (AMERICAS));
    public final static Country COMOROS = new Country("comoros", "km", "com", ".km", (R.string.comoros), (R.drawable.comoros), (AFRICA));
    public final static Country COOK_ISLANDS = new Country("cook_islands", "ck", "cok", ".ck", (R.string.cook_islands), (R.drawable.cook_islands), (OCEANIA));
    public final static Country COSTA_RICA = new Country("costa_rica", "cr", "cri", ".cr", (R.string.costa_rica), (R.drawable.costa_rica), (AMERICAS));
    public final static Country CROATIA = new Country("croatia", "hr", "hrv", ".hr", (R.string.croatia), (R.drawable.croatia), (EUROPE));
    public final static Country CUBA = new Country("cuba", "cu", "cub", ".cu", (R.string.cuba), (R.drawable.cuba), (AMERICAS));
    public final static Country CURACAO = new Country("curacao", "cw", "cuw", ".cw", (R.string.curacao), (R.drawable.curacao), (AMERICAS));
    public final static Country CYPRUS = new Country("cyprus", "cy", "cyp", ".cy", (R.string.cyprus), (R.drawable.cyprus), (EUROPE));
    public final static Country CZECH_REPUBLIC = new Country("czech_republic", "cz", "cze", ".cz", (R.string.czech_republic), (R.drawable.czech_republic), (EUROPE));
    public final static Country DENMARK = new Country("denmark", "dk", "dnk", ".dk", (R.string.denmark), (R.drawable.denmark), (EUROPE));
    public final static Country DJIBOUTI = new Country("djibouti", "dj", "dji", ".dj", (R.string.djibouti), (R.drawable.djibouti), (AFRICA));
    public final static Country DOMINICA = new Country("dominica", "dm", "dma", ".dm", (R.string.dominica), (R.drawable.dominica), (AMERICAS));
    public final static Country DOMINICAN_REPUBLIC = new Country("dominican_republic", "do", "dom", ".do", (R.string.dominican_republic), (R.drawable.dominican_republic), (AMERICAS));
    public final static Country EAST_TIMOR = new Country("east_timor", "tl", "tls", ".tl", (R.string.east_timor), (R.drawable.east_timor), (ASIA));
    public final static Country ECUADOR = new Country("ecuador", "ec", "ecu", ".ec", (R.string.ecuador), (R.drawable.ecuador), (AMERICAS));
    public final static Country EGYPT = new Country("egypt", "eg", "egy", ".eg", (R.string.egypt), (R.drawable.egypt), (AFRICA));
    public final static Country EQUATORIAL_GUINEA = new Country("equatorial_guinea", "gq", "gnq", ".gq", (R.string.equatorial_guinea), (R.drawable.equatorial_guinea), (AFRICA));
    public final static Country ESTONIA = new Country("estonia", "ee", "est", ".ee", (R.string.estonia), (R.drawable.estonia), (EUROPE));
    public final static Country ETHIOPIA = new Country("ethiopia", "et", "eth", ".et", (R.string.ethiopia), (R.drawable.ethiopia), (AFRICA));
    public final static Country FALKLAND_ISLANDS = new Country("falkland_islands", "fk", "flk", ".fk", (R.string.falkland_islands), (R.drawable.falkland_islands), (AMERICAS));
    public final static Country FAROE_ISLANDS = new Country("faroe_islands", "fo", "fro", ".fo", (R.string.faroe_islands), (R.drawable.faroe_islands), (EUROPE));
    public final static Country FIJI = new Country("fiji", "fj", "fji", ".fj", (R.string.fiji), (R.drawable.fiji), (OCEANIA));
    public final static Country FINLAND = new Country("finland", "fi", "fin", ".fi", (R.string.finland), (R.drawable.finland), (EUROPE));
    public final static Country FRANCE = new Country("france", "fr", "fra", ".fr", (R.string.france), (R.drawable.france), (EUROPE));
    public final static Country FRENCH_POLYNESIA = new Country("french_polynesia", "pf", "pyf", ".pf", (R.string.french_polynesia), (R.drawable.french_polynesia), (OCEANIA));
    public final static Country GABON = new Country("gabon", "ga", "gab", ".ga", (R.string.gabon), (R.drawable.gabon), (AFRICA));
    public final static Country GAMBIA = new Country("gambia", "gm", "gmb", ".gm", (R.string.gambia), (R.drawable.gambia), (AFRICA));
    public final static Country GEORGIA = new Country("georgia", "ge", "geo", ".ge", (R.string.georgia), (R.drawable.georgia), (ASIA));
    public final static Country GERMANY = new Country("germany", "de", "deu", ".de", (R.string.germany), (R.drawable.germany), (EUROPE));
    public final static Country GHANA = new Country("ghana", "gh", "gha", ".gh", (R.string.ghana), (R.drawable.ghana), (AFRICA));
    public final static Country GIBRALTAR = new Country("gibraltar", "gi", "gib", ".gi", (R.string.gibraltar), (R.drawable.gibraltar), (EUROPE));
    public final static Country GREECE = new Country("greece", "gr", "grc", ".gr", (R.string.greece), (R.drawable.greece), (EUROPE));
    public final static Country GREENLAND = new Country("greenland", "gl", "grl", ".gl", (R.string.greenland), (R.drawable.greenland), (AMERICAS));
    public final static Country GRENADA = new Country("grenada", "gd", "grd", ".gd", (R.string.grenada), (R.drawable.grenada), (AMERICAS));
    public final static Country GUAM = new Country("guam", "gu", "gum", ".gu", (R.string.guam), (R.drawable.guam), (OCEANIA));
    public final static Country GUATEMALA = new Country("guatemala", "gt", "gtm", ".gt", (R.string.guatemala), (R.drawable.guatemala), (AMERICAS));
    public final static Country GUERNSEY = new Country("guernsey", "gg", "ggy", ".gg", (R.string.guernsey), (R.drawable.guernsey), (EUROPE));
    public final static Country GUINEA = new Country("guinea", "gn", "gin", ".gn", (R.string.guinea), (R.drawable.guinea), (AFRICA));
    public final static Country GUINEA_BISSAU = new Country("guinea_bissau", "gw", "gnb", ".gw", (R.string.guinea_bissau), (R.drawable.guinea_bissau), (AFRICA));
    public final static Country GUYANA = new Country("guyana", "gy", "guy", ".gy", (R.string.guyana), (R.drawable.guyana), (AMERICAS));
    public final static Country HAITI = new Country("haiti", "ht", "hti", ".ht", (R.string.haiti), (R.drawable.haiti), (AMERICAS));
    public final static Country HONDURAS = new Country("honduras", "hn", "hnd", ".hn", (R.string.honduras), (R.drawable.honduras), (AMERICAS));
    public final static Country HONG_KONG = new Country("hong_kong", "hk", "hkg", ".hk", (R.string.hong_kong), (R.drawable.hong_kong), (ASIA));
    public final static Country HUNGARY = new Country("hungary", "hu", "hun", ".hu", (R.string.hungary), (R.drawable.hungary), (EUROPE));
    public final static Country ICELAND = new Country("iceland", "is", "isl", ".is", (R.string.iceland), (R.drawable.iceland), (EUROPE));
    public final static Country INDIA = new Country("india", "in", "ind", ".in", (R.string.india), (R.drawable.india), (ASIA));
    public final static Country INDONESIA = new Country("indonesia", "id", "idn", ".id", (R.string.indonesia), (R.drawable.indonesia), (ASIA));
    public final static Country IRAN = new Country("iran", "ir", "irn", ".ir", (R.string.iran), (R.drawable.iran), (ASIA));
    public final static Country IRAQ = new Country("iraq", "iq", "irq", ".iq", (R.string.iraq), (R.drawable.iraq), (ASIA));
    public final static Country IRELAND = new Country("ireland", "ie", "irl", ".ie", (R.string.ireland), (R.drawable.ireland), (EUROPE));
    public final static Country ISLE_OF_MAN = new Country("isle_of_man", "im", "imn", ".im", (R.string.isle_of_man), (R.drawable.isle_of_man), (EUROPE));
    public final static Country ISRAEL = new Country("israel", "il", "isr", ".il", (R.string.israel), (R.drawable.israel), (ASIA));
    public final static Country ITALY = new Country("italy", "it", "ita", ".it", (R.string.italy), (R.drawable.italy), (EUROPE));
    public final static Country IVORY_COAST = new Country("ivory_coast", "ci", "civ", ".ci", (R.string.ivory_coast), (R.drawable.ivory_coast), (AFRICA));
    public final static Country JAMAICA = new Country("jamaica", "jm", "jam", ".jm", (R.string.jamaica), (R.drawable.jamaica), (AMERICAS));
    public final static Country JAPAN = new Country("japan", "jp", "jpn", ".jp", (R.string.japan), (R.drawable.japan), (ASIA));
    public final static Country JERSEY = new Country("jersey", "je", "jey", ".je", (R.string.jersey), (R.drawable.jersey), (EUROPE));
    public final static Country JORDAN = new Country("jordan", "jo", "jor", ".jo", (R.string.jordan), (R.drawable.jordan), (ASIA));
    public final static Country KAZAKHSTAN = new Country("kazakhstan", "kz", "kaz", ".kz", (R.string.kazakhstan), (R.drawable.kazakhstan), (ASIA));
    public final static Country KENYA = new Country("kenya", "ke", "ken", ".ke", (R.string.kenya), (R.drawable.kenya), (AFRICA));
    public final static Country KIRIBATI = new Country("kiribati", "ki", "kir", ".ki", (R.string.kiribati), (R.drawable.kiribati), (OCEANIA));
    public final static Country KOSOVO = new Country("kosovo", "xk", "unk", "", (R.string.kosovo), (R.drawable.kosovo), (EUROPE));
    public final static Country KUWAIT = new Country("kuwait", "kw", "kwt", ".kw", (R.string.kuwait), (R.drawable.kuwait), (ASIA));
    public final static Country KYRGYZSTAN = new Country("kyrgyzstan", "kg", "kgz", ".kg", (R.string.kyrgyzstan), (R.drawable.kyrgyzstan), (ASIA));
    public final static Country LAOS = new Country("laos", "la", "lao", ".la", (R.string.laos), (R.drawable.laos), (ASIA));
    public final static Country LATVIA = new Country("latvia", "lv", "lva", ".lv", (R.string.latvia), (R.drawable.latvia), (EUROPE));
    public final static Country LEBANON = new Country("lebanon", "lb", "lbn", ".lb", (R.string.lebanon), (R.drawable.lebanon), (ASIA));
    public final static Country LESOTHO = new Country("lesotho", "ls", "lso", ".ls", (R.string.lesotho), (R.drawable.lesotho), (AFRICA));
    public final static Country LIBERIA = new Country("liberia", "lr", "lbr", ".lr", (R.string.liberia), (R.drawable.liberia), (AFRICA));
    public final static Country LIBYA = new Country("libya", "ly", "lby", ".ly", (R.string.libya), (R.drawable.libya), (AFRICA));
    public final static Country LIECHTENSTEIN = new Country("liechtenstein", "li", "lie", ".li", (R.string.liechtenstein), (R.drawable.liechtenstein), (EUROPE));
    public final static Country LITHUANIA = new Country("lithuania", "lt", "ltu", ".lt", (R.string.lithuania), (R.drawable.lithuania), (EUROPE));
    public final static Country LUXEMBOURG = new Country("luxembourg", "lu", "lux", ".lu", (R.string.luxembourg), (R.drawable.luxembourg), (EUROPE));
    public final static Country MACAO = new Country("macao", "mo", "mac", ".mo", (R.string.macao), (R.drawable.macao), (ASIA));
    public final static Country MADAGASCAR = new Country("madagascar", "mg", "mdg", ".mg", (R.string.madagascar), (R.drawable.madagascar), (AFRICA));
    public final static Country MALAWI = new Country("malawi", "mw", "mwi", ".mw", (R.string.malawi), (R.drawable.malawi), (AFRICA));
    public final static Country MALAYSIA = new Country("malaysia", "my", "mys", ".my", (R.string.malaysia), (R.drawable.malaysia), (ASIA));
    public final static Country MALDIVES = new Country("maldives", "mv", "mdv", ".mv", (R.string.maldives), (R.drawable.maldives), (ASIA));
    public final static Country MALI = new Country("mali", "ml", "mli", ".ml", (R.string.mali), (R.drawable.mali), (AFRICA));
    public final static Country MALTA = new Country("malta", "mt", "mlt", ".mt", (R.string.malta), (R.drawable.malta), (EUROPE));
    public final static Country MARSHALL_ISLAND = new Country("marshall_island", "mh", "mhl", ".mh", (R.string.marshall_island), (R.drawable.marshall_island), (OCEANIA));
    public final static Country MARTINIQUE = new Country("martinique", "mq", "mtq", ".mq", (R.string.martinique), (R.drawable.martinique), (AMERICAS));
    public final static Country MAURITANIA = new Country("mauritania", "mr", "mrt", ".mr", (R.string.mauritania), (R.drawable.mauritania), (AFRICA));
    public final static Country MAURITIUS = new Country("mauritius", "mu", "mus", ".mu", (R.string.mauritius), (R.drawable.mauritius), (AFRICA));
    public final static Country MEXICO = new Country("mexico", "mx", "mex", ".mx", (R.string.mexico), (R.drawable.mexico), (AMERICAS));
    public final static Country MICRONESIA = new Country("micronesia", "fm", "fsm", ".fm", (R.string.micronesia), (R.drawable.micronesia), (OCEANIA));
    public final static Country MOLDOVA = new Country("moldova", "md", "mda", ".md", (R.string.moldova), (R.drawable.moldova), (EUROPE));
    public final static Country MONACO = new Country("monaco", "mc", "mco", ".mc", (R.string.monaco), (R.drawable.monaco), (EUROPE));
    public final static Country MONGOLIA = new Country("mongolia", "mn", "mng", ".mn", (R.string.mongolia), (R.drawable.mongolia), (ASIA));
    public final static Country MONTENEGRO = new Country("montenegro", "me", "mne", ".me", (R.string.montenegro), (R.drawable.montenegro), (EUROPE));
    public final static Country MONTSERRAT = new Country("montserrat", "ms", "msr", ".ms", (R.string.montserrat), (R.drawable.montserrat), (AMERICAS));
    public final static Country MOROCCO = new Country("morocco", "ma", "mar", ".ma", (R.string.morocco), (R.drawable.morocco), (AFRICA));
    public final static Country MOZAMBIQUE = new Country("mozambique", "mz", "moz", ".mz", (R.string.mozambique), (R.drawable.mozambique), (AFRICA));
    public final static Country MYANMAR = new Country("myanmar", "mm", "mmr", ".mm", (R.string.myanmar), (R.drawable.myanmar), (ASIA));
    public final static Country NAMIBIA = new Country("namibia", "na", "nam", ".na", (R.string.namibia), (R.drawable.namibia), (AFRICA));
    public final static Country NAURU = new Country("nauru", "nr", "nru", ".nr", (R.string.nauru), (R.drawable.nauru), (OCEANIA));
    public final static Country NEPAL = new Country("nepal", "np", "npl", ".np", (R.string.nepal), (R.drawable.nepal), (ASIA));
    public final static Country NETHERLANDS = new Country("netherlands", "nl", "nld", ".nl", (R.string.netherlands), (R.drawable.netherlands), (EUROPE));
    public final static Country NEW_ZEALAND = new Country("new_zealand", "nz", "nzl", ".nz", (R.string.new_zealand), (R.drawable.new_zealand), (OCEANIA));
    public final static Country NICARAGUA = new Country("nicaragua", "ni", "nic", ".ni", (R.string.nicaragua), (R.drawable.nicaragua), (AMERICAS));
    public final static Country NIGER = new Country("niger", "ne", "ner", ".ne", (R.string.niger), (R.drawable.niger), (AFRICA));
    public final static Country NIGERIA = new Country("nigeria", "ng", "nga", ".ng", (R.string.nigeria), (R.drawable.nigeria), (AFRICA));
    public final static Country NIUE = new Country("niue", "nu", "niu", ".nu", (R.string.niue), (R.drawable.niue), (OCEANIA));
    public final static Country NORFOLK_ISLAND = new Country("norfolk_island", "nf", "nfk", ".nf", (R.string.norfolk_island), (R.drawable.norfolk_island), (OCEANIA));
    public final static Country NORTH_KOREA = new Country("north_korea", "kp", "prk", ".kp", (R.string.north_korea), (R.drawable.north_korea), (ASIA));
    public final static Country NORTHERN_MARIANAS_ISLANDS = new Country("northern_marianas_islands", "mp", "mnp", ".mp", (R.string.northern_marianas_islands), (R.drawable.northern_marianas_islands), (OCEANIA));
    public final static Country NORWAY = new Country("norway", "no", "nor", ".no", (R.string.norway), (R.drawable.norway), (EUROPE));
    public final static Country OMAN = new Country("oman", "om", "omn", ".om", (R.string.oman), (R.drawable.oman), (ASIA));
    public final static Country PAKISTAN = new Country("pakistan", "pk", "pak", ".pk", (R.string.pakistan), (R.drawable.pakistan), (ASIA));
    public final static Country PALAU = new Country("palau", "pw", "plw", ".pw", (R.string.palau), (R.drawable.palau), (OCEANIA));
    public final static Country PALESTINE = new Country("palestine", "ps", "pse", ".ps", (R.string.palestine), (R.drawable.palestine), (ASIA));
    public final static Country PANAMA = new Country("panama", "pa", "pan", ".pa", (R.string.panama), (R.drawable.panama), (AMERICAS));
    public final static Country PAPUA_NEW_GUINEA = new Country("papua_new_guinea", "pg", "png", ".pg", (R.string.papua_new_guinea), (R.drawable.papua_new_guinea), (OCEANIA));
    public final static Country PARAGUAY = new Country("paraguay", "py", "pry", ".py", (R.string.paraguay), (R.drawable.paraguay), (AMERICAS));
    public final static Country PERU = new Country("peru", "pe", "per", ".pe", (R.string.peru), (R.drawable.peru), (AMERICAS));
    public final static Country PHILIPPINES = new Country("philippines", "ph", "phl", ".ph", (R.string.philippines), (R.drawable.philippines), (ASIA));
    public final static Country PITCAIRN_ISLANDS = new Country("pitcairn_islands", "pn", "pcn", ".pn", (R.string.pitcairn_islands), (R.drawable.pitcairn_islands), (OCEANIA));
    public final static Country PORTUGAL = new Country("portugal", "pt", "prt", ".pt", (R.string.portugal), (R.drawable.portugal), (EUROPE));
    public final static Country PUERTO_RICO = new Country("puerto_rico", "pr", "pri", ".pr", (R.string.puerto_rico), (R.drawable.puerto_rico), (AMERICAS));
    public final static Country QATAR = new Country("qatar", "qa", "qat", ".qa", (R.string.qatar), (R.drawable.qatar), (ASIA));
    public final static Country ROMANIA = new Country("romania", "ro", "rou", ".ro", (R.string.romania), (R.drawable.romania), (EUROPE));
    public final static Country RUSSIA = new Country("russia", "ru", "rus", ".ru", (R.string.russia), (R.drawable.russia), (EUROPE));
    public final static Country RWANDA = new Country("rwanda", "rw", "rwa", ".rw", (R.string.rwanda), (R.drawable.rwanda), (AFRICA));
    public final static Country SAMOA = new Country("samoa", "ws", "wsm", ".ws", (R.string.samoa), (R.drawable.samoa), (OCEANIA));
    public final static Country SAN_MARINO = new Country("san_marino", "sm", "smr", ".sm", (R.string.san_marino), (R.drawable.san_marino), (EUROPE));
    public final static Country SAO_TOME_AND_PRINCIPE = new Country("sao_tome_and_principe", "st", "stp", ".st", (R.string.sao_tome_and_principe), (R.drawable.sao_tome_and_principe), (AFRICA));
    public final static Country SAUDI_ARABIA = new Country("saudi_arabia", "sa", "sau", ".sa", (R.string.saudi_arabia), (R.drawable.saudi_arabia), (ASIA));
    public final static Country SENEGAL = new Country("senegal", "sn", "sen", ".sn", (R.string.senegal), (R.drawable.senegal), (AFRICA));
    public final static Country SERBIA = new Country("serbia", "rs", "srb", ".rs", (R.string.serbia), (R.drawable.serbia), (EUROPE));
    public final static Country SEYCHELLES = new Country("seychelles", "sc", "syc", ".sc", (R.string.seychelles), (R.drawable.seychelles), (AFRICA));
    public final static Country SIERRA_LEONE = new Country("sierra_leone", "sl", "sle", ".sl", (R.string.sierra_leone), (R.drawable.sierra_leone), (AFRICA));
    public final static Country SINGAPORE = new Country("singapore", "sg", "sgp", ".sg", (R.string.singapore), (R.drawable.singapore), (ASIA));
    public final static Country SLOVENIA = new Country("slovenia", "si", "svn", ".si", (R.string.slovenia), (R.drawable.slovenia), (EUROPE));
    public final static Country SOLOMON_ISLANDS = new Country("solomon_islands", "sb", "slb", ".sb", (R.string.solomon_islands), (R.drawable.solomon_islands), (OCEANIA));
    public final static Country SOMALIA = new Country("somalia", "so", "som", ".so", (R.string.somalia), (R.drawable.somalia), (AFRICA));
    public final static Country SOUTH_AFRICA = new Country("south_africa", "za", "zaf", ".za", (R.string.south_africa), (R.drawable.south_africa), (AFRICA));
    public final static Country SOUTH_KOREA = new Country("south_korea", "kr", "kor", ".kr", (R.string.south_korea), (R.drawable.south_korea), (ASIA));
    public final static Country SOUTH_SUDAN = new Country("south_sudan", "ss", "ssd", ".ss", (R.string.south_sudan), (R.drawable.south_sudan), (AFRICA));
    public final static Country SPAIN = new Country("spain", "es", "esp", ".es", (R.string.spain), (R.drawable.spain), (EUROPE));
    public final static Country SRI_LANKA = new Country("sri_lanka", "lk", "lka", ".lk", (R.string.sri_lanka), (R.drawable.sri_lanka), (ASIA));
    public final static Country ST_LUCIA = new Country("st_lucia", "lc", "lca", ".lc", (R.string.st_lucia), (R.drawable.st_lucia), (AMERICAS));
    public final static Country ST_VINCENT_AND_THE_GRENADINES = new Country("st_vincent_and_the_grenadines", "vc", "vct", ".vc", (R.string.st_vincent_and_the_grenadines), (R.drawable.st_vincent_and_the_grenadines), (AMERICAS));
    public final static Country SUDAN = new Country("sudan", "sd", "sdn", ".sd", (R.string.sudan), (R.drawable.sudan), (AFRICA));
    public final static Country SURINAME = new Country("suriname", "sr", "sur", ".sr", (R.string.suriname), (R.drawable.suriname), (AMERICAS));
    public final static Country SWAZILAND = new Country("swaziland", "sz", "swz", ".sz", (R.string.swaziland), (R.drawable.swaziland), (AFRICA));
    public final static Country SWEDEN = new Country("sweden", "se", "swe", ".se", (R.string.sweden), (R.drawable.sweden), (EUROPE));
    public final static Country SWITZERLAND = new Country("switzerland", "ch", "che", ".ch", (R.string.switzerland), (R.drawable.switzerland), (EUROPE));
    public final static Country SYRIA = new Country("syria", "sy", "syr", ".sy", (R.string.syria), (R.drawable.syria), (ASIA));
    public final static Country TAIWAN = new Country("taiwan", "tw", "twn", ".tw", (R.string.taiwan), (R.drawable.taiwan), (ASIA));
    public final static Country TAJIKISTAN = new Country("tajikistan", "tj", "tjk", ".tj", (R.string.tajikistan), (R.drawable.tajikistan), (ASIA));
    public final static Country TANZANIA = new Country("tanzania", "tz", "tza", ".tz", (R.string.tanzania), (R.drawable.tanzania), (AFRICA));
    public final static Country THAILAND = new Country("thailand", "th", "tha", ".th", (R.string.thailand), (R.drawable.thailand), (ASIA));
    public final static Country TOGO = new Country("togo", "tg", "tgo", ".tg", (R.string.togo), (R.drawable.togo), (AFRICA));
    public final static Country TOKELAU = new Country("tokelau", "tk", "tkl", ".tk", (R.string.tokelau), (R.drawable.tokelau), (OCEANIA));
    public final static Country TONGA = new Country("tonga", "to", "ton", ".to", (R.string.tonga), (R.drawable.tonga), (OCEANIA));
    public final static Country TRINIDAD_AND_TOBAGO = new Country("trinidad_and_tobago", "tt", "tto", ".tt", (R.string.trinidad_and_tobago), (R.drawable.trinidad_and_tobago), (AMERICAS));
    public final static Country TUNISIA = new Country("tunisia", "tn", "tun", ".tn", (R.string.tunisia), (R.drawable.tunisia), (AFRICA));
    public final static Country TURKEY = new Country("turkey", "tr", "tur", ".tr", (R.string.turkey), (R.drawable.turkey), (ASIA));
    public final static Country TURKMENISTAN = new Country("turkmenistan", "tm", "tkm", ".tm", (R.string.turkmenistan), (R.drawable.turkmenistan), (ASIA));
    public final static Country TURKS_AND_CAICOS = new Country("turks_and_caicos", "tc", "tca", ".tc", (R.string.turks_and_caicos), (R.drawable.turks_and_caicos), (AMERICAS));
    public final static Country TUVALU = new Country("tuvalu", "tv", "tuv", ".tv", (R.string.tuvalu), (R.drawable.tuvalu), (OCEANIA));
    public final static Country UGANDA = new Country("uganda", "ug", "uga", ".ug", (R.string.uganda), (R.drawable.uganda), (AFRICA));
    public final static Country UKRAINE = new Country("ukraine", "ua", "ukr", ".ua", (R.string.ukraine), (R.drawable.ukraine), (EUROPE));
    public final static Country UNITED_ARAB_EMIRATES = new Country("united_arab_emirates", "ae", "are", ".ae", (R.string.united_arab_emirates), (R.drawable.united_arab_emirates), (ASIA));
    public final static Country UNITED_KINGDOM = new Country("united_kingdom", "gb", "gbr", ".uk", (R.string.united_kingdom), (R.drawable.united_kingdom), (EUROPE));
    public final static Country UNITED_STATES_OF_AMERICA = new Country("united_states_of_america", "us", "usa", ".us", (R.string.united_states_of_america), (R.drawable.united_states_of_america), (AMERICAS));
    public final static Country URUGUAY = new Country("uruguay", "uy", "ury", ".uy", (R.string.uruguay), (R.drawable.uruguay), (AMERICAS));
    public final static Country UZBEKISTN = new Country("uzbekistn", "uz", "uzb", ".uz", (R.string.uzbekistn), (R.drawable.uzbekistn), (ASIA));
    public final static Country VANUATU = new Country("vanuatu", "vu", "vut", ".vu", (R.string.vanuatu), (R.drawable.vanuatu), (OCEANIA));
    public final static Country VATICAN_CITY = new Country("vatican_city", "va", "vat", ".va", (R.string.vatican_city), (R.drawable.vatican_city), (EUROPE));
    public final static Country VENEZUELA = new Country("venezuela", "ve", "ven", ".ve", (R.string.venezuela), (R.drawable.venezuela), (AMERICAS));
    public final static Country VIETNAM = new Country("vietnam", "vn", "vnm", ".vn", (R.string.vietnam), (R.drawable.vietnam), (ASIA));
    public final static Country YEMEN = new Country("yemen", "ye", "yem", ".ye", (R.string.yemen), (R.drawable.yemen), (ASIA));
    public final static Country ZAMBIA = new Country("zambia", "zm", "zmb", ".zm", (R.string.zambia), (R.drawable.zambia), (AFRICA));
    public final static Country ZIMBABWE = new Country("zimbabwe", "zw", "zwe", ".zw", (R.string.zimbabwe), (R.drawable.zimbabwe), (AFRICA));
    public final static Country UNITED_NATIONS = new Country("united_nations", "", "", "", (R.string.united_nations), (R.drawable.united_nations), (UNKNOWN));
    public final static Country[] WORLD = new Country[] {AFGHANISTAN, ALAND_ISLANDS, ALBANIA, ALGERIA, AMERICAN_SAMOA, ANDORRA, ANGOLA, ANGUILLA, ANTIGUA_AND_BARBUDA, ARGENTINA, ARMENIA, ARUBA, AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS, BELGIUM, BELIZE, BENIN, BERMUDA, BHUTAN, BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BRAZIL, BRITISH_INDIAN_OCEAN_TERRITORY, BRITISH_VIRGIN_ISLANDS, BRUNEI, BULGARIA, BURKINA_FASO, BURUNDI, CAMBODIA, CAMEROON, CANADA, CAPE_VERDE, CAYMAN_ISLANDS, CENTRAL_AFRICAN_REPUBLIC, CHAD, CHILE, CHINA, CHRISTMAS_ISLAND, COCOS_ISLAND, COLOMBIA, COMOROS, COOK_ISLANDS, COSTA_RICA, CROATIA, CUBA, CURACAO, CYPRUS, CZECH_REPUBLIC, DENMARK, DJIBOUTI, DOMINICA, DOMINICAN_REPUBLIC, EAST_TIMOR, ECUADOR, EGYPT, EQUATORIAL_GUINEA, ESTONIA, ETHIOPIA, FALKLAND_ISLANDS, FAROE_ISLANDS, FIJI, FINLAND, FRANCE, FRENCH_POLYNESIA, GABON, GAMBIA, GEORGIA, GERMANY, GHANA, GIBRALTAR, GREECE, GREENLAND, GRENADA, GUAM, GUATEMALA, GUERNSEY, GUINEA, GUINEA_BISSAU, GUYANA, HAITI, HONDURAS, HONG_KONG, HUNGARY, ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISLE_OF_MAN, ISRAEL, ITALY, IVORY_COAST, JAMAICA, JAPAN, JERSEY, JORDAN, KAZAKHSTAN, KENYA, KIRIBATI, KOSOVO, KUWAIT, KYRGYZSTAN, LAOS, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACAO, MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI, MALTA, MARSHALL_ISLAND, MARTINIQUE, MAURITANIA, MAURITIUS, MEXICO, MICRONESIA, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MONTSERRAT, MOROCCO, MOZAMBIQUE, MYANMAR, NAMIBIA, NAURU, NEPAL, NETHERLANDS, NEW_ZEALAND, NICARAGUA, NIGER, NIGERIA, NIUE, NORFOLK_ISLAND, NORTH_KOREA, NORTHERN_MARIANAS_ISLANDS, NORWAY, OMAN, PAKISTAN, PALAU, PALESTINE, PANAMA, PAPUA_NEW_GUINEA, PARAGUAY, PERU, PHILIPPINES, PITCAIRN_ISLANDS, PORTUGAL, PUERTO_RICO, QATAR, ROMANIA, RUSSIA, RWANDA, SAMOA, SAN_MARINO, SAO_TOME_AND_PRINCIPE, SAUDI_ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA_LEONE, SINGAPORE, SLOVENIA, SOLOMON_ISLANDS, SOMALIA, SOUTH_AFRICA, SOUTH_KOREA, SOUTH_SUDAN, SPAIN, SRI_LANKA, ST_LUCIA, ST_VINCENT_AND_THE_GRENADINES, SUDAN, SURINAME, SWAZILAND, SWEDEN, SWITZERLAND, SYRIA, TAIWAN, TAJIKISTAN, TANZANIA, THAILAND, TOGO, TOKELAU, TONGA, TRINIDAD_AND_TOBAGO, TUNISIA, TURKEY, TURKMENISTAN, TURKS_AND_CAICOS, TUVALU, UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, UNITED_KINGDOM, UNITED_STATES_OF_AMERICA, URUGUAY, UZBEKISTN, VANUATU, VATICAN_CITY, VENEZUELA, VIETNAM, YEMEN, ZAMBIA, ZIMBABWE };

    static {
        WORLD_MAP.put("af", AFGHANISTAN);
        WORLD_MAP.put("ax", ALAND_ISLANDS);
        WORLD_MAP.put("al", ALBANIA);
        WORLD_MAP.put("dz", ALGERIA);
        WORLD_MAP.put("as", AMERICAN_SAMOA);
        WORLD_MAP.put("ad", ANDORRA);
        WORLD_MAP.put("ao", ANGOLA);
        WORLD_MAP.put("ai", ANGUILLA);
        WORLD_MAP.put("ag", ANTIGUA_AND_BARBUDA);
        WORLD_MAP.put("ar", ARGENTINA);
        WORLD_MAP.put("am", ARMENIA);
        WORLD_MAP.put("aw", ARUBA);
        WORLD_MAP.put("au", AUSTRALIA);
        WORLD_MAP.put("at", AUSTRIA);
        WORLD_MAP.put("az", AZERBAIJAN);
        WORLD_MAP.put("bs", BAHAMAS);
        WORLD_MAP.put("bh", BAHRAIN);
        WORLD_MAP.put("bd", BANGLADESH);
        WORLD_MAP.put("bb", BARBADOS);
        WORLD_MAP.put("by", BELARUS);
        WORLD_MAP.put("be", BELGIUM);
        WORLD_MAP.put("bz", BELIZE);
        WORLD_MAP.put("bj", BENIN);
        WORLD_MAP.put("bm", BERMUDA);
        WORLD_MAP.put("bt", BHUTAN);
        WORLD_MAP.put("bo", BOLIVIA);
        WORLD_MAP.put("ba", BOSNIA_AND_HERZEGOVINA);
        WORLD_MAP.put("bw", BOTSWANA);
        WORLD_MAP.put("br", BRAZIL);
        WORLD_MAP.put("io", BRITISH_INDIAN_OCEAN_TERRITORY);
        WORLD_MAP.put("vg", BRITISH_VIRGIN_ISLANDS);
        WORLD_MAP.put("bn", BRUNEI);
        WORLD_MAP.put("bg", BULGARIA);
        WORLD_MAP.put("bf", BURKINA_FASO);
        WORLD_MAP.put("bi", BURUNDI);
        WORLD_MAP.put("kh", CAMBODIA);
        WORLD_MAP.put("cm", CAMEROON);
        WORLD_MAP.put("ca", CANADA);
        WORLD_MAP.put("cv", CAPE_VERDE);
        WORLD_MAP.put("ky", CAYMAN_ISLANDS);
        WORLD_MAP.put("cf", CENTRAL_AFRICAN_REPUBLIC);
        WORLD_MAP.put("td", CHAD);
        WORLD_MAP.put("cl", CHILE);
        WORLD_MAP.put("cn", CHINA);
        WORLD_MAP.put("cx", CHRISTMAS_ISLAND);
        WORLD_MAP.put("cc", COCOS_ISLAND);
        WORLD_MAP.put("co", COLOMBIA);
        WORLD_MAP.put("km", COMOROS);
        WORLD_MAP.put("ck", COOK_ISLANDS);
        WORLD_MAP.put("cr", COSTA_RICA);
        WORLD_MAP.put("hr", CROATIA);
        WORLD_MAP.put("cu", CUBA);
        WORLD_MAP.put("cw", CURACAO);
        WORLD_MAP.put("cy", CYPRUS);
        WORLD_MAP.put("cz", CZECH_REPUBLIC);
        WORLD_MAP.put("dk", DENMARK);
        WORLD_MAP.put("dj", DJIBOUTI);
        WORLD_MAP.put("dm", DOMINICA);
        WORLD_MAP.put("do", DOMINICAN_REPUBLIC);
        WORLD_MAP.put("tl", EAST_TIMOR);
        WORLD_MAP.put("ec", ECUADOR);
        WORLD_MAP.put("eg", EGYPT);
        WORLD_MAP.put("gq", EQUATORIAL_GUINEA);
        WORLD_MAP.put("ee", ESTONIA);
        WORLD_MAP.put("et", ETHIOPIA);
        WORLD_MAP.put("fk", FALKLAND_ISLANDS);
        WORLD_MAP.put("fo", FAROE_ISLANDS);
        WORLD_MAP.put("fj", FIJI);
        WORLD_MAP.put("fi", FINLAND);
        WORLD_MAP.put("fr", FRANCE);
        WORLD_MAP.put("pf", FRENCH_POLYNESIA);
        WORLD_MAP.put("ga", GABON);
        WORLD_MAP.put("gm", GAMBIA);
        WORLD_MAP.put("ge", GEORGIA);
        WORLD_MAP.put("de", GERMANY);
        WORLD_MAP.put("gh", GHANA);
        WORLD_MAP.put("gi", GIBRALTAR);
        WORLD_MAP.put("gr", GREECE);
        WORLD_MAP.put("gl", GREENLAND);
        WORLD_MAP.put("gd", GRENADA);
        WORLD_MAP.put("gu", GUAM);
        WORLD_MAP.put("gt", GUATEMALA);
        WORLD_MAP.put("gg", GUERNSEY);
        WORLD_MAP.put("gn", GUINEA);
        WORLD_MAP.put("gw", GUINEA_BISSAU);
        WORLD_MAP.put("gy", GUYANA);
        WORLD_MAP.put("ht", HAITI);
        WORLD_MAP.put("hn", HONDURAS);
        WORLD_MAP.put("hk", HONG_KONG);
        WORLD_MAP.put("hu", HUNGARY);
        WORLD_MAP.put("is", ICELAND);
        WORLD_MAP.put("in", INDIA);
        WORLD_MAP.put("id", INDONESIA);
        WORLD_MAP.put("ir", IRAN);
        WORLD_MAP.put("iq", IRAQ);
        WORLD_MAP.put("ie", IRELAND);
        WORLD_MAP.put("im", ISLE_OF_MAN);
        WORLD_MAP.put("il", ISRAEL);
        WORLD_MAP.put("it", ITALY);
        WORLD_MAP.put("ci", IVORY_COAST);
        WORLD_MAP.put("jm", JAMAICA);
        WORLD_MAP.put("jp", JAPAN);
        WORLD_MAP.put("je", JERSEY);
        WORLD_MAP.put("jo", JORDAN);
        WORLD_MAP.put("kz", KAZAKHSTAN);
        WORLD_MAP.put("ke", KENYA);
        WORLD_MAP.put("ki", KIRIBATI);
        WORLD_MAP.put("xk", KOSOVO);
        WORLD_MAP.put("kw", KUWAIT);
        WORLD_MAP.put("kg", KYRGYZSTAN);
        WORLD_MAP.put("la", LAOS);
        WORLD_MAP.put("lv", LATVIA);
        WORLD_MAP.put("lb", LEBANON);
        WORLD_MAP.put("ls", LESOTHO);
        WORLD_MAP.put("lr", LIBERIA);
        WORLD_MAP.put("ly", LIBYA);
        WORLD_MAP.put("li", LIECHTENSTEIN);
        WORLD_MAP.put("lt", LITHUANIA);
        WORLD_MAP.put("lu", LUXEMBOURG);
        WORLD_MAP.put("mo", MACAO);
        WORLD_MAP.put("mg", MADAGASCAR);
        WORLD_MAP.put("mw", MALAWI);
        WORLD_MAP.put("my", MALAYSIA);
        WORLD_MAP.put("mv", MALDIVES);
        WORLD_MAP.put("ml", MALI);
        WORLD_MAP.put("mt", MALTA);
        WORLD_MAP.put("mh", MARSHALL_ISLAND);
        WORLD_MAP.put("mq", MARTINIQUE);
        WORLD_MAP.put("mr", MAURITANIA);
        WORLD_MAP.put("mu", MAURITIUS);
        WORLD_MAP.put("mx", MEXICO);
        WORLD_MAP.put("fm", MICRONESIA);
        WORLD_MAP.put("md", MOLDOVA);
        WORLD_MAP.put("mc", MONACO);
        WORLD_MAP.put("mn", MONGOLIA);
        WORLD_MAP.put("me", MONTENEGRO);
        WORLD_MAP.put("ms", MONTSERRAT);
        WORLD_MAP.put("ma", MOROCCO);
        WORLD_MAP.put("mz", MOZAMBIQUE);
        WORLD_MAP.put("mm", MYANMAR);
        WORLD_MAP.put("na", NAMIBIA);
        WORLD_MAP.put("nr", NAURU);
        WORLD_MAP.put("np", NEPAL);
        WORLD_MAP.put("nl", NETHERLANDS);
        WORLD_MAP.put("nz", NEW_ZEALAND);
        WORLD_MAP.put("ni", NICARAGUA);
        WORLD_MAP.put("ne", NIGER);
        WORLD_MAP.put("ng", NIGERIA);
        WORLD_MAP.put("nu", NIUE);
        WORLD_MAP.put("nf", NORFOLK_ISLAND);
        WORLD_MAP.put("kp", NORTH_KOREA);
        WORLD_MAP.put("mp", NORTHERN_MARIANAS_ISLANDS);
        WORLD_MAP.put("no", NORWAY);
        WORLD_MAP.put("om", OMAN);
        WORLD_MAP.put("pk", PAKISTAN);
        WORLD_MAP.put("pw", PALAU);
        WORLD_MAP.put("ps", PALESTINE);
        WORLD_MAP.put("pa", PANAMA);
        WORLD_MAP.put("pg", PAPUA_NEW_GUINEA);
        WORLD_MAP.put("py", PARAGUAY);
        WORLD_MAP.put("pe", PERU);
        WORLD_MAP.put("ph", PHILIPPINES);
        WORLD_MAP.put("pn", PITCAIRN_ISLANDS);
        WORLD_MAP.put("pt", PORTUGAL);
        WORLD_MAP.put("pr", PUERTO_RICO);
        WORLD_MAP.put("qa", QATAR);
        WORLD_MAP.put("ro", ROMANIA);
        WORLD_MAP.put("ru", RUSSIA);
        WORLD_MAP.put("rw", RWANDA);
        WORLD_MAP.put("ws", SAMOA);
        WORLD_MAP.put("sm", SAN_MARINO);
        WORLD_MAP.put("st", SAO_TOME_AND_PRINCIPE);
        WORLD_MAP.put("sa", SAUDI_ARABIA);
        WORLD_MAP.put("sn", SENEGAL);
        WORLD_MAP.put("rs", SERBIA);
        WORLD_MAP.put("sc", SEYCHELLES);
        WORLD_MAP.put("sl", SIERRA_LEONE);
        WORLD_MAP.put("sg", SINGAPORE);
        WORLD_MAP.put("si", SLOVENIA);
        WORLD_MAP.put("sb", SOLOMON_ISLANDS);
        WORLD_MAP.put("so", SOMALIA);
        WORLD_MAP.put("za", SOUTH_AFRICA);
        WORLD_MAP.put("kr", SOUTH_KOREA);
        WORLD_MAP.put("ss", SOUTH_SUDAN);
        WORLD_MAP.put("es", SPAIN);
        WORLD_MAP.put("lk", SRI_LANKA);
        WORLD_MAP.put("lc", ST_LUCIA);
        WORLD_MAP.put("vc", ST_VINCENT_AND_THE_GRENADINES);
        WORLD_MAP.put("sd", SUDAN);
        WORLD_MAP.put("sr", SURINAME);
        WORLD_MAP.put("sz", SWAZILAND);
        WORLD_MAP.put("se", SWEDEN);
        WORLD_MAP.put("ch", SWITZERLAND);
        WORLD_MAP.put("sy", SYRIA);
        WORLD_MAP.put("tw", TAIWAN);
        WORLD_MAP.put("tj", TAJIKISTAN);
        WORLD_MAP.put("tz", TANZANIA);
        WORLD_MAP.put("th", THAILAND);
        WORLD_MAP.put("tg", TOGO);
        WORLD_MAP.put("tk", TOKELAU);
        WORLD_MAP.put("to", TONGA);
        WORLD_MAP.put("tt", TRINIDAD_AND_TOBAGO);
        WORLD_MAP.put("tn", TUNISIA);
        WORLD_MAP.put("tr", TURKEY);
        WORLD_MAP.put("tm", TURKMENISTAN);
        WORLD_MAP.put("tc", TURKS_AND_CAICOS);
        WORLD_MAP.put("tv", TUVALU);
        WORLD_MAP.put("ug", UGANDA);
        WORLD_MAP.put("ua", UKRAINE);
        WORLD_MAP.put("ae", UNITED_ARAB_EMIRATES);
        WORLD_MAP.put("gb", UNITED_KINGDOM);
        WORLD_MAP.put("us", UNITED_STATES_OF_AMERICA);
        WORLD_MAP.put("uy", URUGUAY);
        WORLD_MAP.put("uz", UZBEKISTN);
        WORLD_MAP.put("vu", VANUATU);
        WORLD_MAP.put("va", VATICAN_CITY);
        WORLD_MAP.put("ve", VENEZUELA);
        WORLD_MAP.put("vn", VIETNAM);
        WORLD_MAP.put("ye", YEMEN);
        WORLD_MAP.put("zm", ZAMBIA);
        WORLD_MAP.put("zw", ZIMBABWE);
    }

}
